version: "2"

networks:
  nw:
    driver: bridge

services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Test@5201314
    ports:
      - "3306:3306"
    networks:
      - nw
  api:
    build: ./api
    ports:
      - "4000:4000"
    networks:
      - nw
    depends_on:
      - mysql
  app:
    build: ./app
    ports:
      - "3000:3000"
    networks:
      - nw
    depends_on:
      - mysql
      - api

